[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Projects & Publications"
URL = "project"
weight = 3

[[Languages.en.menu.main]]
name = "Services"
URL = "service"
weight = 4

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 5
  
[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 7


# footer menu
[[Languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[Languages.en.menu.footer]]
name = "Project"
URL = "project"
weight = 2

[[Languages.en.menu.footer]]
name = "Service"
URL = "service"
weight = 3

[[Languages.en.menu.footer]]
name = "Pricing"
URL = "pricing"
weight = 4

[[Languages.en.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6